---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedoom
  namespace: kubedoom
spec:
  selector:
    matchLabels:
      run: kubedoom
  replicas: 1
  template:
    metadata:
      labels:
        run: kubedoom
    spec:
      hostNetwork: true
      serviceAccountName: kubedoom
      containers:
        - name: kubedoom
          image: storaxdev/kubedoom:0.5.0
          ports:
            - containerPort: 5900
              protocol: TCP

#пробрасываем порт
#  kubectl port-forward kubedoom-* 5900:5900 --namespace=kubedoom